database:
  host: localhost
  port: 3306
  user: root
  pass: p@ssow0rd
  name: data
  tables:
    plot: "plots"
    town: "towns"
    state: "states"
    resident: "residents"
    user: "users"
    stats: "stats"
taxes:
  town_creation: 5000
  state_creation: 25000
  plot_town_claim: 100
